### ISSUE TITLE
Add RSS feed ability 

### ISSUE THREAD

**Issue by shannaniggans** [shannaniggans/fancy4n6.github.io#1]
Enable feedly function

**Comment by ScottyAU** [comment]
Absolutely happy to test this when needed :)

**Comment by shannaniggans** [comment]
> Absolutely happy to test this when needed :)

Have implemented the basic plugin and looked in feedly and appears to work, please let me know what else i should configure to make it better and readable!

**Comment by ScottyAU** [comment]
https://fancy4n6.com/feed.xml - works perfectly for me (I use my own categories in feedly already)....

**Comment by shannaniggans** [comment]
RSS feed added and updated
